"""
Synthetic email dataset.
Each email has a ground-truth label used by graders.
"""

EMAILS = [
    # ── SPAM ──────────────────────────────────────────────────────────────────
    {
        "email_id": "e001",
        "subject": "Congratulations! You've won $1,000,000",
        "sender": "winner@prize-claim-now.xyz",
        "sender_domain": "prize-claim-now.xyz",
        "body": "Dear valued customer, you have been selected as our lucky winner. Click here to claim your prize immediately. Limited time offer!",
        "has_attachment": False,
        "word_count": 28,
        "gt_category": "spam",
        "gt_priority": 5,
        "gt_department": "ignore",
        "gt_should_reply": False,
    },
    {
        "email_id": "e002",
        "subject": "FREE VIAGRA - 80% discount!!!",
        "sender": "deals@pharma-cheap.ru",
        "sender_domain": "pharma-cheap.ru",
        "body": "Best prices on medication. No prescription needed. Buy now and save big. Click the link below.",
        "has_attachment": True,
        "word_count": 18,
        "gt_category": "spam",
        "gt_priority": 5,
        "gt_department": "ignore",
        "gt_should_reply": False,
    },
    {
        "email_id": "e003",
        "subject": "Verify your account NOW or lose access",
        "sender": "security@bankofamerica-verify.com",
        "sender_domain": "bankofamerica-verify.com",
        "body": "Your account has been compromised. Verify immediately by clicking the link and entering your credentials. Failure to act will result in permanent suspension.",
        "has_attachment": False,
        "word_count": 31,
        "gt_category": "spam",
        "gt_priority": 5,
        "gt_department": "ignore",
        "gt_should_reply": False,
    },
    # ── URGENT ────────────────────────────────────────────────────────────────
    {
        "email_id": "e004",
        "subject": "URGENT: Production database is DOWN",
        "sender": "alerts@monitoring.company.com",
        "sender_domain": "company.com",
        "body": "CRITICAL ALERT: Production database server db-prod-01 is not responding. All services affected. Error rate: 100%. Started: 2 minutes ago. Immediate action required.",
        "has_attachment": False,
        "word_count": 30,
        "gt_category": "urgent",
        "gt_priority": 1,
        "gt_department": "engineering",
        "gt_should_reply": True,
    },
    {
        "email_id": "e005",
        "subject": "Security breach detected - immediate response needed",
        "sender": "cso@company.com",
        "sender_domain": "company.com",
        "body": "We have detected unauthorized access to our systems. All hands on deck. Please join the war room call immediately. This is a P0 incident.",
        "has_attachment": False,
        "word_count": 33,
        "gt_category": "urgent",
        "gt_priority": 1,
        "gt_department": "engineering",
        "gt_should_reply": True,
    },
    {
        "email_id": "e006",
        "subject": "Contract deadline TODAY - needs signature",
        "sender": "legal@bigclient.com",
        "sender_domain": "bigclient.com",
        "body": "Hi, we need the signed contract back by 5 PM today or the deal is void. Please have your CEO sign and send back ASAP. This is time sensitive.",
        "has_attachment": True,
        "word_count": 34,
        "gt_category": "urgent",
        "gt_priority": 1,
        "gt_department": "management",
        "gt_should_reply": True,
    },
    {
        "email_id": "e007",
        "subject": "Server memory at 98% - intervention needed",
        "sender": "nagios@infra.company.com",
        "sender_domain": "company.com",
        "body": "WARNING: Server web-prod-03 memory utilization has reached 98%. System may crash soon if not addressed. Please investigate immediately.",
        "has_attachment": False,
        "word_count": 27,
        "gt_category": "urgent",
        "gt_priority": 2,
        "gt_department": "engineering",
        "gt_should_reply": False,
    },
    # ── NORMAL ────────────────────────────────────────────────────────────────
    {
        "email_id": "e008",
        "subject": "Question about your API pricing",
        "sender": "john.developer@startup.io",
        "sender_domain": "startup.io",
        "body": "Hi, I'm evaluating your API for our startup. Could you share the pricing plans and whether you offer startup discounts? We're expecting around 10M requests per month. Thanks!",
        "has_attachment": False,
        "word_count": 32,
        "gt_category": "normal",
        "gt_priority": 3,
        "gt_department": "sales",
        "gt_should_reply": True,
    },
    {
        "email_id": "e009",
        "subject": "Bug report: Login fails on Safari",
        "sender": "customer123@gmail.com",
        "sender_domain": "gmail.com",
        "body": "Hello, I've been trying to log in using Safari 16 on macOS and it just spins forever. Chrome works fine. Please fix this as I can't access my account.",
        "has_attachment": False,
        "word_count": 34,
        "gt_category": "normal",
        "gt_priority": 2,
        "gt_department": "engineering",
        "gt_should_reply": True,
    },
    {
        "email_id": "e010",
        "subject": "Invoice #4521 - Payment due",
        "sender": "billing@vendor-supplies.com",
        "sender_domain": "vendor-supplies.com",
        "body": "Please find attached Invoice #4521 for $2,340 due on March 15, 2024. Please process payment at your earliest convenience. Late fees apply after due date.",
        "has_attachment": True,
        "word_count": 31,
        "gt_category": "normal",
        "gt_priority": 3,
        "gt_department": "management",
        "gt_should_reply": True,
    },
    {
        "email_id": "e011",
        "subject": "Request for feature: Dark mode",
        "sender": "user.feedback@outlook.com",
        "sender_domain": "outlook.com",
        "body": "Love the product! One thing that would make it much better is dark mode. Any plans for this? Many users in the community have been asking for it too.",
        "has_attachment": False,
        "word_count": 30,
        "gt_category": "normal",
        "gt_priority": 4,
        "gt_department": "support",
        "gt_should_reply": True,
    },
    {
        "email_id": "e012",
        "subject": "Partnership opportunity discussion",
        "sender": "partnerships@techcorp.com",
        "sender_domain": "techcorp.com",
        "body": "Hi, we're TechCorp and we're interested in exploring a partnership with your company. We serve 50,000 enterprise clients and see strong synergies. Can we schedule a call this week?",
        "has_attachment": False,
        "word_count": 35,
        "gt_category": "normal",
        "gt_priority": 2,
        "gt_department": "sales",
        "gt_should_reply": True,
    },
    # ── NEWSLETTER ────────────────────────────────────────────────────────────
    {
        "email_id": "e013",
        "subject": "This week in tech: AI roundup",
        "sender": "newsletter@techdigest.com",
        "sender_domain": "techdigest.com",
        "body": "This week's top stories: OpenAI releases GPT-5. Google announces new chips. Tesla's autonomous driving update. Subscribe to our premium tier for in-depth analysis. Unsubscribe anytime.",
        "has_attachment": False,
        "word_count": 35,
        "gt_category": "newsletter",
        "gt_priority": 5,
        "gt_department": "ignore",
        "gt_should_reply": False,
    },
    {
        "email_id": "e014",
        "subject": "Your monthly SaaS analytics digest",
        "sender": "digest@saasmetrics.io",
        "sender_domain": "saasmetrics.io",
        "body": "Monthly digest: Industry averages, churn rates, growth benchmarks. Your peers grew 15% last month. Read the full report. Manage subscription preferences below.",
        "has_attachment": False,
        "word_count": 28,
        "gt_category": "newsletter",
        "gt_priority": 5,
        "gt_department": "ignore",
        "gt_should_reply": False,
    },
    # ── INTERNAL ──────────────────────────────────────────────────────────────
    {
        "email_id": "e015",
        "subject": "Q2 planning meeting - Thursday 3pm",
        "sender": "ceo@company.com",
        "sender_domain": "company.com",
        "body": "Team, we have our Q2 planning session this Thursday at 3pm in Conference Room B. Please come prepared with your team's OKRs and resource requirements. Attendance is mandatory.",
        "has_attachment": False,
        "word_count": 33,
        "gt_category": "internal",
        "gt_priority": 2,
        "gt_department": "management",
        "gt_should_reply": False,
    },
    {
        "email_id": "e016",
        "subject": "New hire starting Monday - please welcome Sarah",
        "sender": "hr@company.com",
        "sender_domain": "company.com",
        "body": "Excited to announce Sarah Chen joins us as Senior Engineer on Monday. Please give her a warm welcome. Her manager will be Alex. Onboarding details attached.",
        "has_attachment": True,
        "word_count": 29,
        "gt_category": "internal",
        "gt_priority": 4,
        "gt_department": "hr",
        "gt_should_reply": False,
    },
    {
        "email_id": "e017",
        "subject": "Payroll update: new reimbursement policy",
        "sender": "payroll@company.com",
        "sender_domain": "company.com",
        "body": "Starting next month, the expense reimbursement limit increases to $500/month. Submit receipts within 30 days. New form is attached. Contact HR with questions.",
        "has_attachment": True,
        "word_count": 27,
        "gt_category": "internal",
        "gt_priority": 3,
        "gt_department": "hr",
        "gt_should_reply": False,
    },
    {
        "email_id": "e018",
        "subject": "CRITICAL: Customer data export script corrupted data",
        "sender": "dba@company.com",
        "sender_domain": "company.com",
        "body": "The overnight data export job for customer-segment-B ran with a bug and may have corrupted 2,300 records. I've stopped the job. Need immediate DBA and engineering review. This affects billing.",
        "has_attachment": False,
        "word_count": 37,
        "gt_category": "urgent",
        "gt_priority": 1,
        "gt_department": "engineering",
        "gt_should_reply": True,
    },
    {
        "email_id": "e019",
        "subject": "Can I get a refund? Very disappointed",
        "sender": "angry.customer@hotmail.com",
        "sender_domain": "hotmail.com",
        "body": "I've been a customer for 2 years and your latest update broke everything I rely on. This is unacceptable. I want a full refund immediately or I'm disputing with my credit card company.",
        "has_attachment": False,
        "word_count": 36,
        "gt_category": "normal",
        "gt_priority": 2,
        "gt_department": "support",
        "gt_should_reply": True,
    },
    {
        "email_id": "e020",
        "subject": "Unsubscribe me from all emails please",
        "sender": "tired.user@gmail.com",
        "sender_domain": "gmail.com",
        "body": "Please unsubscribe me from all your marketing emails. I've clicked the unsubscribe link three times and still receiving them. This is very frustrating.",
        "has_attachment": False,
        "word_count": 28,
        "gt_category": "normal",
        "gt_priority": 3,
        "gt_department": "support",
        "gt_should_reply": True,
    },
]

VALID_CATEGORIES = {"spam", "urgent", "normal", "newsletter", "internal"}
VALID_DEPARTMENTS = {"sales", "support", "engineering", "hr", "management", "ignore"}
